version: '3'

services:
  php:
    image: php:8.0.2-fpm
    volumes:
      - ./php-app/:/var/www/html:rw
  web:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./php-app/:/var/www/html:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php