apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: php-code
        persistentVolumeClaim:
          claimName: php-code
      containers:
      - name: php
        image: dynamiccommerce.azurecr.io/academy-mw:1.0.0
        imagePullPolicy: Always
        volumeMounts:
          - name: php-code
            mountPath: /usr/share/app
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /var/www/html/. /usr/share/app"]