apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-mw
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
      - name: php-code
        persistentVolumeClaim:
          claimName: php-code
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: default.conf
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-code
          mountPath: /var/www/html
        - name: config
          mountPath: /etc/nginx/conf.d