apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-mw
  labels:
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: backend
  ports:
  - protocol: TCP
    port: 80