apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-code
  namespace: test-mw
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile